name: Warmtescans Rapportages APP CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch: 

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:  Warmtescans Rapportages
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      
      - name: Replace prod environment variable - api base url
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/environment.prod.ts'
          search-text: '@@api-base-url@@'
          replacement-text: '${{ vars.API_BASE_URL }}'
          exclude: 'node_modules/**'
          encoding: 'utf8'

      - name: Replace prod environment variable - google client id
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/environment.prod.ts'
          search-text: '@@google-client-id@@'
          replacement-text: '${{ secrets.GOOGLE_CLIENT_ID }}'
          exclude: 'node_modules/**'
          encoding: 'utf8'
     
      - name: Install dependencies
        run: npm ci
        working-directory: ./ERH.HeatScans.Reporting/erh.heatscans.reporting.client

      - name: Build 
        id: build
        run: npm run build:prod -- --base-href "/ERH-Warmtescans/"
        working-directory: ./ERH.HeatScans.Reporting/erh.heatscans.reporting.client

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: nielander.nl
          protocol: ftps
          username: ${{ secrets.hostuser }}
          password: ${{ secrets.hostpwd }}
          local-dir: ./ERH.HeatScans.Reporting/erh.heatscans.reporting.client/dist/erh.heatscans.reporting.client/browser/
          server-dir: /v024501c/ERH-Warmtescans/
          log-level: verbose

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"












