# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - erh-warmtescans-rapportage-api

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore NuGet packages (FLIR)
        working-directory: .\ERH.HeatScans.Reporting
        run: nuget restore .\ERH.FLIR\ERH.FLIR.csproj -Verbosity detailed

      - name: Restore NuGet packages (HeatScans.Reporting)
        working-directory: .\ERH.HeatScans.Reporting
        run: nuget restore .\ERH.HeatScans.Reporting\ERH.HeatScans.Reporting.csproj -Verbosity detailed

      - name: Restore NuGet packages (Server)
        working-directory: .\ERH.HeatScans.Reporting
        run: nuget restore .\ERH.HeatScans.Reporting.Server.Framework\ERH.HeatScans.Reporting.Server.Framework.csproj -Verbosity detailed

      - name: Set appSettings.xml
        working-directory: .\ERH.HeatScans.Reporting\ERH.HeatScans.Reporting.Server.Framework
        run: copy .\appSettings.template.xml -Destination .\appSettings.xml 
  
      - name: Env variables
        run: env

        # Replace all placeholders with actual secrets from GitHub Secrets  
      - name: Replace prod environment variable - google client id
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './ERH.HeatScans.Reporting/ERH.HeatScans.Reporting.Server.Framework/appSettings.xml'
          search-text: '@@YOUR_CLIENT_ID@@'
          replacement-text: ${{ secrets.GOOGLE_CLIENT_ID }}
          encoding: 'utf8'

      - name: Replace prod environment variable - users folder id
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '.\ERH.HeatScans.Reporting\ERH.HeatScans.Reporting.Server.Framework\appSettings.xml'
          search-text: '@@UsersFolderId@@'
          replacement-text: ${{ secrets.DRIVE_USERS_FOLDER_ID }}
          encoding: 'utf8'

      - name: Replace prod environment variable - google maps api key
        uses: richardrigutins\replace-in-files@v2
        with:
          files: '.\ERH.HeatScans.Reporting\ERH.HeatScans.Reporting.Server.Framework\appSettings.xml'
          search-text: '@@YOUR_GOOGLE_MAPS_API_KEY@@'
          replacement-text: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          encoding: 'utf8'

      - name: AppSettings
        run: cat .\ERH.HeatScans.Reporting\ERH.HeatScans.Reporting.Server.Framework\appSettings.xml
