# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Warmtescans Rapportages API CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build:
    runs-on: windows-latest
    environment:  Warmtescans Rapportages
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore NuGet packages (FLIR)
        working-directory: .\ERH.HeatScans.Reporting
        run: nuget restore .\ERH.FLIR\ERH.FLIR.csproj 

      - name: Restore NuGet packages (HeatScans.Reporting)
        working-directory: .\ERH.HeatScans.Reporting
        run: nuget restore .\ERH.HeatScans.Reporting\ERH.HeatScans.Reporting.csproj 

      - name: Restore NuGet packages (Wheather)
        working-directory: .\ERH.HeatScans.Reporting
        run: nuget restore .\ERH.HeatScans.Reporting.Server.Framework\ERH.HeatScans.Reporting.Server.Framework.csproj

      - name: Restore NuGet packages (Server)
        working-directory: .\ERH.HeatScans.Reporting
        run: nuget restore .\ERH.Weather.Client\ERH.Weather.Client.csproj

      - name: Set Web.config
        working-directory: .\ERH.HeatScans.Reporting\ERH.HeatScans.Reporting.Server.Framework
        run: copy .\Web.config.template -Destination .\Web.config 

        # Replace all placeholders with actual secrets from GitHub Secrets  
      - name: Replace prod environment variable - google client id
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './ERH.HeatScans.Reporting/ERH.HeatScans.Reporting.Server.Framework/Web.config'
          search-text: '@@YOUR_CLIENT_ID@@'
          replacement-text: ${{ secrets.GOOGLE_CLIENT_ID }}
          encoding: 'utf8'

      - name: Replace prod environment variable - users folder id
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './ERH.HeatScans.Reporting/ERH.HeatScans.Reporting.Server.Framework/Web.config'
          search-text: '@@YOUR_GOOGLE_DRIVE_FOLDER_ID@@'
          replacement-text: ${{ secrets.DRIVE_USERS_FOLDER_ID }}
          encoding: 'utf8'

      - name: Replace prod environment variable - google maps api key
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './ERH.HeatScans.Reporting/ERH.HeatScans.Reporting.Server.Framework/Web.config'
          search-text: '@@YOUR_GOOGLE_MAPS_API_KEY@@'
          replacement-text: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          encoding: 'utf8'

      - name: Replace prod environment variable - API root url
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './ERH.HeatScans.Reporting/ERH.HeatScans.Reporting.Server.Framework/Web.config'
          search-text: '@@API_ROOT_URL@@'
          replacement-text: "${{ vars.API_BASE_URL }}"
          encoding: 'utf8'

      - name: Replace prod environment variable - CORS
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './ERH.HeatScans.Reporting/ERH.HeatScans.Reporting.Server.Framework/Web.config'
          search-text: '@@CORS_ALLOWED_ORIGINS@@'
          replacement-text: "https://nielander.nl"
          encoding: 'utf8'

      - name: Publish to folder
        working-directory: .\ERH.HeatScans.Reporting
        run: msbuild .\ERH.HeatScans.Reporting.Server.Framework\ERH.HeatScans.Reporting.Server.Framework.csproj /nologo /verbosity:m /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:PublishUrl="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '\published\**'

  deploy:
    runs-on: windows-latest
    environment:  Warmtescans Rapportages
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: ?? Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: nielander.nl
          protocol: ftps
          username: ${{ secrets.hostuser }}
          password: ${{ secrets.hostpwd }}
          local-dir: ./
          server-dir: /v024501c/ERH-Warmtescans-Api

          log-level: verbose

